src/main/java/org/apache/commons/collections4/comparators/FixedOrderComparator.java
map is a final value initialized to an object and can never be null.
=> [FixedOrderComparator] Simplify always false condition

src/main/java/org/apache/commons/collections4/bidimap/DualTreeBidiMap.java, src/test/java/org/apache/commons/collections4/BulkTest.java, src/test/java/org/apache/commons/collections4/bidimap/DualTreeBidiMap2Test.java, src/test/java/org/apache/commons/collections4/bidimap/DualTreeBidiMapTest.java, src/test/java/org/apache/commons/collections4/map/AbstractMapTest.java, src/test/java/org/apache/commons/collections4/map/TransformedSortedMapTest.java, src/test/java/org/apache/commons/collections4/trie/UnmodifiableTrieTest.java
Considering that we now require Java 8, having a workaround for IBM's
version of JDK 1.6 isn't required.
=> [BulkTest] remove workarounds for buggy JDK 1.6 implementations

pom.xml
Use source=8 for maven-javadoc-plugin. Build passing on JDK 11 for me, on Ubuntu LTS, Maven 3.5.4.
Hoping Travis will pass too.
=> Fix Travis build

src/main/java/org/apache/commons/collections4/map/LRUMap.java
The exception error message does not include an '=' before every field.
=> Fix LRUMap exception message

src/main/java/org/apache/commons/collections4/ListUtils.java, src/main/java/org/apache/commons/collections4/list/LazyList.java, src/test/java/org/apache/commons/collections4/ListUtilsTest.java, src/test/java/org/apache/commons/collections4/list/LazyListTest.java
This change adds support for `Transformer` in the `LazyList` class.
Some test cases have been added since I could not find any tests for `LazyList`. However, the class does not seem to be serializable as stated in the Javadoc.
=> [COLLECTIONS-694] Support Transformer for LazyList

src/main/java/org/apache/commons/collections4/Closure.java, src/main/java/org/apache/commons/collections4/Factory.java, src/main/java/org/apache/commons/collections4/Predicate.java, src/main/java/org/apache/commons/collections4/Transformer.java, src/main/java/org/apache/commons/collections4/map/PassiveExpiringMap.java, src/main/java/org/apache/commons/collections4/sequence/ReplacementsHandler.java
Now that we're using Java 8, it seems reasonable to annotate.
=> global: make use of FunctionalInterface

src/main/java/org/apache/commons/collections4/iterators/CollatingIterator.java
change the index boundary from `> size()` to` >= size()`
for the `setIterator(final int index, final Iterator<? extends E> iterator)` method in the class `org.apache.commons.collections4.iterators.CollatingIterator<E>`.
=> [Collections-727] fix the potential misleading comment

src/test/java/org/apache/commons/collections4/collection/TransformedCollectionTest.java, src/test/java/org/apache/commons/collections4/map/LazySortedMapTest.java, src/test/java/org/apache/commons/collections4/map/PredicatedSortedMapTest.java, src/test/java/org/apache/commons/collections4/map/TransformedMapTest.java
I used this project as a learning tool for getting familiar with [Pitest](http://pitest.org/) mutation testing and picked a few test classes to improve based on the result. I picked the below classes because the current test suite provides 100% line coverage, but PIT found surviving mutants.
In the `TransformedMapTest` class, the `testFactory_decorateTransform` method did not provide a key transformer. In `TransformedMap::transformedMap` the call to `decorated.clear()` is only necessary if the key transformer changes the key set. This adds a test with a key transformer.
Both `LazySortedMap` and `PredicatedMap` have tests that check if the comparator is null, but never check for a non-null value. The added tests check that if a non-null comparator is used then it is properly returned.
=> Added additional tests for map classes based on mutation results

src/main/java/org/apache/commons/collections4/CollectionUtils.java, src/test/java/org/apache/commons/collections4/CollectionUtilsTest.java
For [COLLECTIONS-674](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-674?filter=allopenissues)
=> [COLLECTIONS-674] Add drain method to CollectionUtils

src/site/xdoc/index.xml, src/site/xdoc/release_4_4.xml
The link on the main page still points to 4.3 and the 4.4 release notes still list the changes from 4.3.
=> Fix links to release notes and update contents for 4.4

src/main/java/org/apache/commons/collections4/bloomfilter/ArrayCountingBloomFilter.java, src/main/java/org/apache/commons/collections4/bloomfilter/BitSetBloomFilter.java, src/test/java/org/apache/commons/collections4/bloomfilter/ArrayCountingBloomFilterTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/BitSetBloomFilterTest.java
fix for COLLECTIONS-763
Removes constructors that initialze the BloomFilter with data via the Hasher argument to the constructor.  The exception is the HasherBloomFilter which by definition wraps a Hasher.
=> Removed constructors that set initial values

src/test/java/org/apache/commons/collections4/CollectionUtilsTest.java
Issue description: https://issues.apache.org/jira/browse/COLLECTIONS-775
This is a rather simple fix -- instead of adding `CollectionUtils.get(expected, 0)` and `CollectionUtils.get(expected, 1)` to a new HashMap (`found`) and compare the two maps, assert the 0 and 1 entries are either `zeroKey=zero` or `oneKey=one`.
=> [COLLECTIONS-775] Fix flaky CollectionUtilsTest.getFromMap()

src/main/java/org/apache/commons/collections4/properties/SortedProperties.java, src/test/java/org/apache/commons/collections4/properties/SortedPropertiesTest.java
At present the `SortedProperties` class overrides & sorts in the `keys()` method, but not the `entrySet()` method. This leads to inconsistencies depending on how the properties are retrieved (for example, when calling `write()` to write the properties to a file, Java 8 uses `keyset()` but Java 11+ uses `entrySet()` - same for other methods like `list()`.)
This PR guarantees the same ordering on `keys()` as `entrySet()`, removing this inconsistency.
(First contribution to this repository, so please feel free to point me in the correct direction if something is wrong!)
=> SortedProperties should sort entrySet() as well as keys()

src/test/java/org/apache/commons/collections4/BagUtilsTest.java, src/test/java/org/apache/commons/collections4/ClosureUtilsTest.java, src/test/java/org/apache/commons/collections4/ListUtilsTest.java, src/test/java/org/apache/commons/collections4/PredicateUtilsTest.java, src/test/java/org/apache/commons/collections4/TrieUtilsTest.java, src/test/java/org/apache/commons/collections4/collection/CompositeCollectionTest.java, src/test/java/org/apache/commons/collections4/functors/AbstractCompositePredicateTest.java, src/test/java/org/apache/commons/collections4/functors/AbstractPredicateTest.java, src/test/java/org/apache/commons/collections4/iterators/ArrayListIteratorTest.java, src/test/java/org/apache/commons/collections4/iterators/FilterListIteratorTest.java, src/test/java/org/apache/commons/collections4/iterators/IteratorEnumerationTest.java, src/test/java/org/apache/commons/collections4/iterators/LoopingIteratorTest.java, src/test/java/org/apache/commons/collections4/iterators/LoopingListIteratorTest.java, src/test/java/org/apache/commons/collections4/iterators/ObjectArrayListIteratorTest.java, src/test/java/org/apache/commons/collections4/keyvalue/AbstractMapEntryTest.java, src/test/java/org/apache/commons/collections4/keyvalue/DefaultKeyValueTest.java, src/test/java/org/apache/commons/collections4/keyvalue/DefaultMapEntryTest.java, src/test/java/org/apache/commons/collections4/keyvalue/MultiKeyTest.java, src/test/java/org/apache/commons/collections4/keyvalue/TiedMapEntryTest.java, src/test/java/org/apache/commons/collections4/keyvalue/UnmodifiableMapEntryTest.java, src/test/java/org/apache/commons/collections4/list/Collections701Test.java, src/test/java/org/apache/commons/collections4/list/FixedSizeListTest.java, src/test/java/org/apache/commons/collections4/properties/AbstractPropertiesFactoryTest.java, src/test/java/org/apache/commons/collections4/properties/PropertiesFactoryTest.java, src/test/java/org/apache/commons/collections4/properties/SortedPropertiesFactoryTest.java, src/test/java/org/apache/commons/collections4/properties/SortedPropertiesTest.java, src/test/java/org/apache/commons/collections4/trie/PatriciaTrieTest.java
Upgrade JUnit v4 Assert to JUnit v5 Assertions.
Any class extending a TestCase will use Assertions.assert...(
Any class not extending a TestCase will use static imports.
=> JUnit v5 Imports

src/changes/changes.xml, src/test/java/org/apache/commons/collections4/properties/EmptyPropertiesTest.java
This fixes the unit test that failed intermittently in GH Actions.
=> [COLLECTIONS-812] Open both streams with try-with-resources, and assert that only the text is the same, not the time

src/main/java/org/apache/commons/collections4/CollectionUtils.java, src/main/java/org/apache/commons/collections4/ListUtils.java, src/main/java/org/apache/commons/collections4/comparators/ComparatorChain.java, src/main/java/org/apache/commons/collections4/comparators/TransformingComparator.java, src/main/java/org/apache/commons/collections4/functors/DefaultEquator.java, src/main/java/org/apache/commons/collections4/map/Flat3Map.java, src/main/java/org/apache/commons/collections4/map/StaticBucketMap.java, src/main/java/org/apache/commons/collections4/multiset/AbstractMultiSet.java, src/main/java/org/apache/commons/collections4/trie/AbstractBitwiseTrie.java
Contributed on behalf of the @opencastsoftware open source team
=> When possible use java.lang.Objects#equals; eliminated a couple of nulls

pom.xml, src/changes/changes.xml, src/test/java/org/apache/commons/collections4/GuavaTestlibTest.java
Adding the test class from @ben-manes, pending merge of #300
=> [COLLECTIONS-811] Integrate Guava Testlib tests for Apache Commons Collections

src/main/java/org/apache/commons/collections4/bloomfilter/ArrayCountingBloomFilter.java
Resolves https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-823
Modifies `ArrayCountingBloomFilter.forEachBitmap()` to be more efficient. by not creating an array of longs but building each long and calling the consumer in turn.
=> COLLECTIONS-823: Modified ArrayCountingBloomFilter.forEachBitMap to be more efficient

src/test/java/org/apache/commons/collections4/bag/CollectionBagTest.java, src/test/java/org/apache/commons/collections4/bag/HashBagTest.java, src/test/java/org/apache/commons/collections4/bag/PredicatedBagTest.java, src/test/java/org/apache/commons/collections4/bag/TransformedBagTest.java, src/test/java/org/apache/commons/collections4/bag/UnmodifiableBagTest.java, src/test/java/org/apache/commons/collections4/bidimap/AbstractBidiMapTest.java, src/test/java/org/apache/commons/collections4/bidimap/DualHashBidiMapTest.java, src/test/java/org/apache/commons/collections4/bidimap/UnmodifiableBidiMapTest.java, src/test/java/org/apache/commons/collections4/collection/AbstractCollectionTest.java, src/test/java/org/apache/commons/collections4/map/AbstractMapTest.java, src/test/java/org/apache/commons/collections4/map/PassiveExpiringMapTest.java, src/test/java/org/apache/commons/collections4/multimap/AbstractMultiValuedMapTest.java, src/test/java/org/apache/commons/collections4/multimap/ArrayListValuedHashMapTest.java, src/test/java/org/apache/commons/collections4/multimap/HashSetValuedHashMapTest.java, src/test/java/org/apache/commons/collections4/multimap/TransformedMultiValuedMapTest.java, src/test/java/org/apache/commons/collections4/multimap/UnmodifiableMultiValuedMapTest.java, src/test/java/org/apache/commons/collections4/multiset/AbstractMultiSetTest.java, src/test/java/org/apache/commons/collections4/multiset/HashMultiSetTest.java, src/test/java/org/apache/commons/collections4/multiset/PredicatedMultiSetTest.java, src/test/java/org/apache/commons/collections4/multiset/SynchronizedMultiSetTest.java, src/test/java/org/apache/commons/collections4/multiset/UnmodifiableMultiSetTest.java, src/test/java/org/apache/commons/collections4/set/CompositeSetTest.java, src/test/java/org/apache/commons/collections4/set/PredicatedSetTest.java, src/test/java/org/apache/commons/collections4/set/TransformedSetTest.java, src/test/java/org/apache/commons/collections4/set/UnmodifiableSetTest.java
- This PR fixes the flaky test  `org.apache.commons.collections4.bag.CollectionBagTest.testCollectionToArray2`
- The mentioned test may fail or pass without changes made to the source code when it is run in different JVMs due to `HashMap`'s non-deterministic iteration order.
- As the `CollectionBagTest` uses `HashBag` as its `collection` which uses `HashMap` internally and as per `Java 8` documentation, the ordering of `HashMap` is not constant, so assigning the same hashmap as an array to different objects can change the ordering. So when comparing these two arrays with `assertEquals` the test may fail as their ordering can be different.
- Run the test with 'NonDex' maven plugin. The command to recreate the flaky test failure is 
` mvn -pl . edu.illinois:nondex-maven-plugin:1.1.2:nondex …
=> Fix flaky test occurred in 'CollectionBagTest.testCollectionToArray2'

src/test/java/org/apache/commons/collections4/bidimap/AbstractBidiMapTest.java
In test : `org.apache.commons.collections4.bidimap.DualHashBidiMapTest#testBidiKeySetValuesOrder`
The order of keyset and valueSet can differ because it uses `HashMap` which is non deterministic so its order cannot be determined.
Replacing `HashMap` with `LinkedHashMap` so the order of keySet and valueSet remains same.
=> [COLLECTIONS-836] fix flaky test DualHashBidiMapTest

src/test/java/org/apache/commons/collections4/CollectionUtilsTest.java
The test below in `CollectionUtilsTest.java` was found flaky because of the ordering of result HashMap. The orders of elements in the HashMap are not the same as every time the test being called. In this case, LinkedHashMap was applied to ensure the orders do not cause the flakiness. This code change is trying to fix the [flaky tests](https://docs.gitlab.com/ee/development/testing_guide/flaky_tests.html) mentioned above, because they sometimes fail (as the picture showed) and sometimes pass. The failure could be reproduced by the commands above by using the tool of [NonDex](https://github.com/TestingResearchIllinois/NonDex). The code change is to make sure the tests will always pass in this case.
- `org.apache.commons.collections4.CollectionUtilsTest.get`
The test failures could be …
=> Fix flaky test in CollectionUtilsTest.Java

src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java, src/test/java/org/apache/commons/collections4/bloomfilter/AbstractBloomFilterTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/ArrayHasher.java, src/test/java/org/apache/commons/collections4/bloomfilter/DefaultIndexProducerTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/IncrementingHasher.java, src/test/java/org/apache/commons/collections4/bloomfilter/TestingHashers.java
Makes some previously package private classes and methods public so that they may be used in developing tests for new Bloom filter implementations.
In addition, a correction for an error where specific cases can lead to a negative value for an estimated intersection.  Test case is provided.
=> Changes required to open testing to new implementations.

src/test/java/org/apache/commons/collections4/bloomfilter/AbstractBloomFilterTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/TestingHashers.java
Changes to test setup to account for Bloom filters that use bit decay (e.g. Stable Bloom filter).   These changes do not change the tests, just the way the filters are configured so that decay based filters will have the proper results.
=> [COLLECTIONS-841] Open up bloom filter tests - test changes to support bit decay based Bloom filters

src/main/java/org/apache/commons/collections4/trie/AbstractPatriciaTrie.java
I extend this class [here](https://github.com/vad0/gfjson/blob/master/src/main/java/org/apache/commons/collections4/trie/AsciiTrie.java) to make an implementation which works with an `AsciiSequenceView` instead of `String`. Package visibility forces me to create a package org.apache.commons.collections4.trie in my project. This hack works, but it prevents me from migrating to the java modules system, which prohibits using the same package names in the different modules. So I think the best solution here wil be to make AbstractPatriciaTrie public.
=> Make AbstractPatriciaTrie public

DEVELOPERS-GUIDE.html, src/main/java/org/apache/commons/collections4/MapUtils.java, src/main/java/org/apache/commons/collections4/MultiMap.java, src/main/java/org/apache/commons/collections4/MultiSet.java, src/main/java/org/apache/commons/collections4/MultiValuedMap.java, src/main/java/org/apache/commons/collections4/PredicateUtils.java, src/main/java/org/apache/commons/collections4/SplitMapUtils.java, src/main/java/org/apache/commons/collections4/TransformerUtils.java, src/main/java/org/apache/commons/collections4/collection/PredicatedCollection.java, src/main/java/org/apache/commons/collections4/functors/WhileClosure.java, src/main/java/org/apache/commons/collections4/iterators/IteratorChain.java, src/main/java/org/apache/commons/collections4/iterators/NodeListIterator.java, src/main/java/org/apache/commons/collections4/iterators/ObjectGraphIterator.java, src/main/java/org/apache/commons/collections4/list/CursorableLinkedList.java, src/main/java/org/apache/commons/collections4/list/NodeCachingLinkedList.java, src/main/java/org/apache/commons/collections4/list/SetUniqueList.java, src/main/java/org/apache/commons/collections4/list/TreeList.java, src/main/java/org/apache/commons/collections4/map/ListOrderedMap.java, src/main/java/org/apache/commons/collections4/map/MultiValueMap.java, src/main/java/org/apache/commons/collections4/sequence/SequencesComparator.java, src/main/java/org/apache/commons/collections4/sequence/package-info.java, src/main/java/org/apache/commons/collections4/trie/KeyAnalyzer.java, src/site/xdoc/history.xml
- fixes misplaced symbols in JavaDoc (mainly in Hasher, CountingLongPredicate)
- resolves grammar and punctuation issues
=> Fix punctuation and minor JavaDoc issues

src/test/java/org/apache/commons/collections4/ArrayUtilsTest.java
The test cases are adapted from https://github.com/apache/commons-lang/blob/master/src/test/java/org/apache/commons/lang3/ArrayUtilsTest.java
=> Add test cases for indexOf and contains method of ArrayUtils class

src/main/java/org/apache/commons/collections4/list/AbstractLinkedListForJava21.java, src/main/java/org/apache/commons/collections4/list/CursorableLinkedList.java, src/main/java/org/apache/commons/collections4/list/NodeCachingLinkedList.java, src/test/java/org/apache/commons/collections4/list/AbstractLinkedListForJava21Test.java, src/test/java/org/apache/commons/collections4/list/DefaultAbstractLinkedListForJava21Test.java
This is a minimal PR. We may need to improve the deprecation notes.
Coverage tests are failing; we'd need to add test coverage for the new variant, which IMHO requires having an implementation using it.
I've verified that this change would work for Jackrabbit, see https://issues.apache.org/jira/browse/JCR-5049 for details.
=> COLLECTIONS-842: deprecate Lists incompatible with Java 21, add new variant of AbstractLinkedList

src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java, src/main/java/org/apache/commons/collections4/bloomfilter/LayerManager.java, src/main/java/org/apache/commons/collections4/bloomfilter/LayeredBloomFilter.java, src/main/java/org/apache/commons/collections4/bloomfilter/WrappedBloomFilter.java, src/test/java/org/apache/commons/collections4/bloomfilter/BitMapProducerFromLayeredBloomFilterTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/BitMapProducerFromWrappedBloomFilterTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/CellProducerFromLayeredBloomFilterTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/LayerManagerTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/LayeredBloomFilterTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/WrappedBloomFilterTest.java
Changes to the is code:
1. Added generics to LayeredBloomFilter and LayerManager so that the implementation of the enclosed Bloom filter can be specified.
2. Modified WrappedBloomfFilter to require copy() implementation.
3.  Changed the LayerManager internal LinkedList declaration to List.
=> COLLECTIONS-853: Change LayerManager to use List and added generics to LayerdedBloomFilter

src/main/java/org/apache/commons/collections4/bloomfilter/EnhancedDoubleHasher.java, src/test/java/org/apache/commons/collections4/bloomfilter/EnhancedDoubleHasherTest.java
Fix for [COLLECTIONS-855](https://issues.apache.org/jira/browse/COLLECTIONS-855)
Modified the loop counters as recommended in bug report.
Adjusted test data accordingly.
=> [COLLECTIONS-855] Fixed hashing calculation as per report

src/main/java/org/apache/commons/collections4/bloomfilter/package-info.java, src/site/markdown/bloomFilters/advanced.md, src/site/markdown/bloomFilters/implementation.md, src/site/markdown/bloomFilters/intro.md, src/site/markdown/bloomFilters/multidimensional.md
This change continues the work on COLLECTIONS-857.
=> [Collections-857] update bloom filter documentation

src/test/java/org/apache/commons/collections4/ListUtilsTest.java
- isEqualList: same size, but different elements in the lists
- isEqualList: same size, same elements, but different order
- hashCodeForList: with null element
- partition.get: edge cases (Exception)
- union: multiple cases
- sum: happy path
=> Increase test coverage for ListUtils

src/main/java/org/apache/commons/collections4/iterators/CartesianProductIterator.java, src/test/java/org/apache/commons/collections4/iterators/CartesianProductIteratorTest.java
The `CartesianProductIterator` is suitable to enhance a deeply-nested for-loops over a set of collections.
Given
```java
var a = new Arrays.asList('a1', 'a2', 'a3');
var b = new Arrays.asList('b1', 'b2', 'b3');
var c = new Arrays.asList('c1', 'c2', 'c3');
var d = new Arrays.asList('d1', 'd2', 'd3');
var e = new Arrays.asList('e1', 'e2', 'e3');
var f = new Arrays.asList('f1', 'f2', 'f3');
```
instead of
```java
for (var aElement : a) {
for (var bElement : b) {
for (var cElement : c) {
for (var dElement : d) {
for (var eElement : e) {
for (var fElement : f) {
// ...
}
}
}
}
}
}
```
it would look like:
```
var it = new CartesianProductIterator<>(a, b, c, d, e, f);
while (it.hasNext()) {
var elements = it.next();
}
```
Extremely useful for nesting levels 10+.
=> [COLLECTIONS-858] CartesianProductIterator
