apache/commons-collections

src/main/java/org/apache/commons/collections4/bidimap/TreeBidiMap.java, src/main/java/org/apache/commons/collections4/collection/CompositeCollection.java, src/main/java/org/apache/commons/collections4/functors/AllPredicate.java, src/main/java/org/apache/commons/collections4/iterators/NodeListIterator.java, src/main/java/org/apache/commons/collections4/iterators/PeekingIterator.java, src/main/java/org/apache/commons/collections4/iterators/PushbackIterator.java, src/main/java/org/apache/commons/collections4/list/AbstractLinkedList.java, src/main/java/org/apache/commons/collections4/multimap/AbstractMultiValuedMap.java, src/test/java/org/apache/commons/collections4/SetUtilsTest.java, src/test/java/org/apache/commons/collections4/functors/AbstractMockPredicateTest.java, src/test/java/org/apache/commons/collections4/keyvalue/MultiKeyTest.java, src/test/java/org/apache/commons/collections4/list/Collections701Test.java
Fix issues like unused imports, unnecessary suppress warning, simplified boolean expressions, and others.
Separated into commits for easier review (and drop if necessary).
Cheers
Bruno
=> Fix site report issues

.gitignore, src/main/java/org/apache/commons/collections4/bag/UnmodifiableBag.java, src/main/java/org/apache/commons/collections4/bag/UnmodifiableSortedBag.java, src/main/java/org/apache/commons/collections4/bidimap/AbstractDualBidiMap.java, src/main/java/org/apache/commons/collections4/collection/AbstractCollectionDecorator.java, src/main/java/org/apache/commons/collections4/collection/CompositeCollection.java, src/main/java/org/apache/commons/collections4/collection/IndexedCollection.java, src/main/java/org/apache/commons/collections4/collection/SynchronizedCollection.java, src/main/java/org/apache/commons/collections4/collection/UnmodifiableBoundedCollection.java, src/main/java/org/apache/commons/collections4/collection/UnmodifiableCollection.java, src/main/java/org/apache/commons/collections4/list/FixedSizeList.java, src/main/java/org/apache/commons/collections4/list/SetUniqueList.java, src/main/java/org/apache/commons/collections4/list/UnmodifiableList.java, src/main/java/org/apache/commons/collections4/map/LinkedMap.java, src/main/java/org/apache/commons/collections4/map/UnmodifiableEntrySet.java, src/main/java/org/apache/commons/collections4/multiset/UnmodifiableMultiSet.java, src/main/java/org/apache/commons/collections4/queue/UnmodifiableQueue.java, src/main/java/org/apache/commons/collections4/set/CompositeSet.java, src/main/java/org/apache/commons/collections4/set/ListOrderedSet.java, src/main/java/org/apache/commons/collections4/set/MapBackedSet.java, src/main/java/org/apache/commons/collections4/set/UnmodifiableNavigableSet.java, src/main/java/org/apache/commons/collections4/set/UnmodifiableSet.java, src/main/java/org/apache/commons/collections4/set/UnmodifiableSortedSet.java, src/test/java/org/apache/commons/collections4/collection/AbstractCollectionTest.java, src/test/java/org/apache/commons/collections4/collection/CompositeCollectionTest.java
- Add removeIf to SynchronizedCollection
- Add mac store files to gitignore
=> Add removeIf

src/changes/changes.xml, src/main/java/org/apache/commons/collections4/properties/AbstractPropertiesFactory.java, src/main/java/org/apache/commons/collections4/properties/PropertiesFactory.java, src/main/java/org/apache/commons/collections4/properties/SortedPropertiesFactory.java, src/test/java/org/apache/commons/collections4/properties/AbstractPropertiesFactoryTest.java, src/test/java/org/apache/commons/collections4/properties/PropertiesFactoryTest.java, src/test/java/org/apache/commons/collections4/properties/SortedPropertiesFactoryTest.java, src/test/resources/properties/test.properties
[COLLECTIONS-719] Create a PropertiesFactory and SortedPropertiesFactory.
=> [COLLECTIONS-719] Create a PropertiesFactory and SortedPropertiesFactory

src/main/java/org/apache/commons/collections4/list/CursorableLinkedList.java, src/main/java/org/apache/commons/collections4/set/ListOrderedSet.java
These are semantically identical easier to read.
=>  Simplify two remove-if loops

.travis.yml
Adding support for travis job on ppc64le architecture.
=> Adding Power support

src/main/java/org/apache/commons/collections4/MultiValuedMap.java
Using in code example class that actually exists, avoidig HTML escapes.
=> [COLLECTIONS-679] Using existing class in example given in Javadocs.

src/test/java/org/apache/commons/collections4/IteratorUtilsTest.java
Add testcases to IteratorUtilsTest
=> Add test cases to IteratorUtilsTest

RELEASE-NOTES.txt, src/main/java/org/apache/commons/collections4/map/AbstractHashedMap.java, src/test/java/org/apache/commons/collections4/map/AbstractMapTest.java
=> find and fix fixtypo

src/main/java/org/apache/commons/collections4/list/GrowthList.java
[COLLECTIONS-704] Update the size to the capacity for GrowthList
=> [COLLECTIONS-704] Update size to capacity for GrowthList

src/test/java/org/apache/commons/collections4/list/GrowthListTest.java
Add a junit for GrowthListTest(int initialCapacity)
=> Add a junit for GrowthListTest(int initialCapacity)

src/test/java/org/apache/commons/collections4/map/UnmodifiableSortedMapTest.java
add a junit for the HeadMap in the UnmodifiableSortedMapTest
=> add a junit for the HeadMap in the UnmodifiableSortedMapTest

src/test/java/org/apache/commons/collections4/map/UnmodifiableSortedMapTest.java
add junit for the subMap and tailMap in the UnmodifiableSortedMapTest
=> Test subMap and tailMap 

src/test/java/org/apache/commons/collections4/multimap/AbstractMultiValuedMapTest.java, src/test/java/org/apache/commons/collections4/multimap/HashSetValuedHashMapTest.java, src/test/java/org/apache/commons/collections4/multimap/TransformedMultiValuedMapTest.java
1.Add three test cases in HashSetValuedHashMapTest
2.Update a test case in AbstractMultiValuedMapTest
3.Update a test case in TransformedMultiValuedMapTest
=> Update some map test cases

src/test/java/org/apache/commons/collections4/queue/CircularFifoQueueTest.java
=> Add three test cases in UnmodifiableQueueTest

src/test/java/org/apache/commons/collections4/multimap/AbstractMultiValuedMapTest.java, src/test/java/org/apache/commons/collections4/multimap/HashSetValuedHashMapTest.java
Add a test case in AbstractMultiValuedMapTest for AbstractMultiValued.MapTest.MultiValuedMapIterator
=> Add a test case AbstractMultiValuedMapTest#testMultiValuedMapIterator()

src/test/java/org/apache/commons/collections4/multimap/ArrayListValuedHashMapTest.java
Add test cases for ArrayListValuedHashMapTest to cover ArrayListValuedHashMap and AbstractListValuedMap
=> Add test cases to ArrayListValuedHashMapTest

src/main/java/org/apache/commons/collections4/TransformerUtils.java, src/main/java/org/apache/commons/collections4/functors/SwitchTransformer.java
See [COLLECTIONS-740](https://issues.apache.org/jira/browse/COLLECTIONS-740).
=> [COLLECTIONS-740] Add missing @throws comment for SwitchTransformer.switchTransformer.

src/main/java/org/apache/commons/collections4/map/DefaultedMap.java, src/test/java/org/apache/commons/collections4/map/DefaultedMapTest.java
See [COLLECTIONS-739](https://issues.apache.org/jira/browse/COLLECTIONS-739).
=> [COLLECTIONS-739] Fix inconsistent @throws comments in DefaultedMap

src/main/java/org/apache/commons/collections4/bloomfilter/AbstractBloomFilter.java, src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilterIndexer.java, src/main/java/org/apache/commons/collections4/bloomfilter/HasherBloomFilter.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/HashFunctionIdentity.java, src/test/java/org/apache/commons/collections4/bloomfilter/BloomFilterIndexerTest.java
This contains various changes to the Bloom filter package as discussed on the developer mailing list.
=> Bloom filter updates

src/main/java/org/apache/commons/collections4/bloomfilter/AbstractBloomFilter.java, src/main/java/org/apache/commons/collections4/bloomfilter/BitSetBloomFilter.java, src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java, src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilterIndexer.java, src/main/java/org/apache/commons/collections4/bloomfilter/HasherBloomFilter.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/DynamicHasher.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/HashFunction.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/HashFunctionIdentity.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/HashFunctionValidator.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/Shape.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/StaticHasher.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/function/MD5Cyclic.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/function/Murmur128x86Cyclic.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/function/Murmur32x86Iterative.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/function/ObjectsHashIterative.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/function/Signatures.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/function/package-info.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/package-info.java, src/test/java/org/apache/commons/collections4/bloomfilter/AbstractBloomFilterTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/BitSetBloomFilterTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/BloomFilterIndexerTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/HasherBloomFilterTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/hasher/ShapeTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/hasher/function/AbstractHashFunctionTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/hasher/function/Murmur128x86CyclicTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/hasher/function/Murmur32x86IterativeTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/hasher/function/ObjectsHashIterativeTest.java
Fixing coverage.
Updating the Shape object with more documentation and fixing the hash code implementation.
=> Bloomfilter updates2

pom.xml
Handles https://issues.apache.org/jira/browse/COLLECTIONS-754
Also based upon https://issues.apache.org/jira/browse/COLLECTIONS-753 branch so pr https://github.com/apache/commons-collections/pull/135
=> COLLECTIONS-754 upgrade to JUnit v5.6.0

src/test/java/org/apache/commons/collections4/map/HashedMapTest.java
Fix https://issues.apache.org/jira/browse/COLLECTIONS-773
=> [COLLECTIONS-773] Add an assertion to validate ensureCapacity

src/main/java/org/apache/commons/collections4/SplitMapUtils.java, src/main/java/org/apache/commons/collections4/bidimap/TreeBidiMap.java, src/main/java/org/apache/commons/collections4/bloomfilter/AbstractBloomFilter.java, src/main/java/org/apache/commons/collections4/bloomfilter/hasher/function/MD5Cyclic.java, src/main/java/org/apache/commons/collections4/comparators/FixedOrderComparator.java, src/main/java/org/apache/commons/collections4/map/DefaultedMap.java, src/main/java/org/apache/commons/collections4/map/LRUMap.java, src/main/java/org/apache/commons/collections4/trie/AbstractPatriciaTrie.java, src/test/java/org/apache/commons/collections4/BulkTest.java, src/test/java/org/apache/commons/collections4/CollectionUtilsTest.java, src/test/java/org/apache/commons/collections4/FluentIterableTest.java, src/test/java/org/apache/commons/collections4/IterableUtilsTest.java, src/test/java/org/apache/commons/collections4/ListUtilsTest.java, src/test/java/org/apache/commons/collections4/junit/AbstractAvailableLocalesTest.java, src/test/java/org/apache/commons/collections4/list/GrowthListTest.java, src/test/java/org/apache/commons/collections4/map/Flat3MapTest.java, src/test/java/org/apache/commons/collections4/multimap/ArrayListValuedHashMapTest.java, src/test/java/org/apache/commons/collections4/multimap/HashSetValuedHashMapTest.java, src/test/java/org/apache/commons/collections4/set/AbstractNavigableSetTest.java, src/test/java/org/apache/commons/collections4/set/AbstractSortedSetTest.java
* Add final
* Unnecessary semicolon ';'
=> Minor Improvements

src/main/java/org/apache/commons/collections4/ArrayUtils.java, src/main/java/org/apache/commons/collections4/CollectionUtils.java, src/main/java/org/apache/commons/collections4/IteratorUtils.java, src/main/java/org/apache/commons/collections4/ListUtils.java, src/main/java/org/apache/commons/collections4/list/AbstractLinkedList.java, src/main/java/org/apache/commons/collections4/map/LinkedMap.java
The idea it's create a constant that represent that the Index to search it's not found
=> [COLLECTIONS-781] - INDEX_NOT_FOUND Constant

src/test/java/org/apache/commons/collections4/AbstractArrayListTest.java, src/test/java/org/apache/commons/collections4/TrieUtilsTest.java, src/test/java/org/apache/commons/collections4/bag/UnmodifiableBagTest.java, src/test/java/org/apache/commons/collections4/bag/UnmodifiableSortedBagTest.java, src/test/java/org/apache/commons/collections4/bidimap/UnmodifiableBidiMapTest.java, src/test/java/org/apache/commons/collections4/bidimap/UnmodifiableOrderedBidiMapTest.java, src/test/java/org/apache/commons/collections4/bidimap/UnmodifiableSortedBidiMapTest.java, src/test/java/org/apache/commons/collections4/collection/IndexedCollectionTest.java, src/test/java/org/apache/commons/collections4/collection/UnmodifiableBoundedCollectionTest.java, src/test/java/org/apache/commons/collections4/collection/UnmodifiableCollectionTest.java, src/test/java/org/apache/commons/collections4/iterators/AbstractOrderedMapIteratorTest.java, src/test/java/org/apache/commons/collections4/iterators/ArrayIteratorTest.java, src/test/java/org/apache/commons/collections4/iterators/FilterIteratorTest.java, src/test/java/org/apache/commons/collections4/iterators/IteratorEnumerationTest.java, src/test/java/org/apache/commons/collections4/iterators/NodeListIteratorTest.java, src/test/java/org/apache/commons/collections4/iterators/ObjectArrayIteratorTest.java, src/test/java/org/apache/commons/collections4/iterators/PermutationIteratorTest.java, src/test/java/org/apache/commons/collections4/iterators/UnmodifiableIteratorTest.java, src/test/java/org/apache/commons/collections4/iterators/UnmodifiableMapIteratorTest.java, src/test/java/org/apache/commons/collections4/iterators/UnmodifiableOrderedMapIteratorTest.java, src/test/java/org/apache/commons/collections4/keyvalue/AbstractMapEntryTest.java, src/test/java/org/apache/commons/collections4/keyvalue/DefaultMapEntryTest.java, src/test/java/org/apache/commons/collections4/keyvalue/UnmodifiableMapEntryTest.java, src/test/java/org/apache/commons/collections4/list/SetUniqueListTest.java, src/test/java/org/apache/commons/collections4/map/CompositeMapTest.java, src/test/java/org/apache/commons/collections4/set/UnmodifiableSetTest.java, src/test/java/org/apache/commons/collections4/trie/PatriciaTrieTest.java, src/test/java/org/apache/commons/collections4/trie/UnmodifiableTrieTest.java
Next batch of JUnit v5 upgrades.
=> COLLECTIONS-777 JUnit v5 assertThrows no1

src/test/java/org/apache/commons/collections4/bloomfilter/SetOperationsTest.java, src/test/java/org/apache/commons/collections4/collection/CompositeCollectionTest.java, src/test/java/org/apache/commons/collections4/collection/PredicatedCollectionTest.java, src/test/java/org/apache/commons/collections4/comparators/ComparatorChainTest.java, src/test/java/org/apache/commons/collections4/functors/CatchAndRethrowClosureTest.java, src/test/java/org/apache/commons/collections4/iterators/ArrayListIteratorTest.java, src/test/java/org/apache/commons/collections4/iterators/ListIteratorWrapper2Test.java, src/test/java/org/apache/commons/collections4/iterators/ObjectArrayListIteratorTest.java, src/test/java/org/apache/commons/collections4/iterators/PeekingIteratorTest.java, src/test/java/org/apache/commons/collections4/keyvalue/DefaultKeyValueTest.java, src/test/java/org/apache/commons/collections4/keyvalue/MultiKeyTest.java, src/test/java/org/apache/commons/collections4/map/MultiValueMapTest.java, src/test/java/org/apache/commons/collections4/map/UnmodifiableMapTest.java, src/test/java/org/apache/commons/collections4/map/UnmodifiableOrderedMapTest.java, src/test/java/org/apache/commons/collections4/map/UnmodifiableSortedMapTest.java
Another set of changed, should not have merge conflicts with other PR.
=> COLLECTIONS-777 JUnit v5 assertThrows no2

src/test/java/org/apache/commons/collections4/ComparatorUtilsTest.java, src/test/java/org/apache/commons/collections4/FactoryUtilsTest.java, src/test/java/org/apache/commons/collections4/MultiSetUtilsTest.java, src/test/java/org/apache/commons/collections4/QueueUtilsTest.java, src/test/java/org/apache/commons/collections4/TransformerUtilsTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/IndexFilterTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/hasher/DynamicHasherBuilderTest.java, src/test/java/org/apache/commons/collections4/bloomfilter/hasher/DynamicHasherTest.java, src/test/java/org/apache/commons/collections4/comparators/BooleanComparatorTest.java, src/test/java/org/apache/commons/collections4/comparators/FixedOrderComparatorTest.java
Same as #281 #282 #283
JUnit v5 assertThrows TransformerUtilsTest
JUnit v5 assertThrows DynamicHasherBuilderTest
JUnit v5 assertThrows DynamicHasherTest
JUnit v5 assertThrows IndexFilterTest
JUnit v5 assertThrows BooleanComparatorTest
JUnit v5 assertThrows FixedOrderComparatorTest
JUnit v5 assertThrows ComparatorUtilsTest
JUnit v5 assertThrows FactoryUtilsTest
JUnit v5 assertThrows MultiSetUtilsTest
JUnit v5 assertThrows QueueUtilsTest
=> COLLECTIONS-777 JUnit v5 assertThrows no4

src/test/java/org/apache/commons/collections4/properties/AbstractPropertiesFactoryTest.java
Found one place not updated. Maybe better to include in other change as it is quite minor.
=> [COLLECTIONS-807] fix one place not updated

src/main/java/org/apache/commons/collections4/bloomfilter/BitMapProducer.java, src/main/java/org/apache/commons/collections4/bloomfilter/CountingLongPredicate.java
Fix [COLLECTIONS-826](https://issues.apache.org/jira/browse/COLLECTIONS-826)
=> Move counting long predicate

src/main/java/org/apache/commons/collections4/bloomfilter/ArrayCountingBloomFilter.java, src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java, src/main/java/org/apache/commons/collections4/bloomfilter/SimpleBloomFilter.java, src/main/java/org/apache/commons/collections4/bloomfilter/SparseBloomFilter.java, src/test/java/org/apache/commons/collections4/bloomfilter/DefaultBloomFilterTest.java
converted BloomFilter.isSparse() to BloomFilter.characteristics() and defiend SPARSE constant.
fixes Collections-818
=> Collections-818: convert to characteristics flag

src/main/java/org/apache/commons/collections4/bloomfilter/BitMap.java, src/main/java/org/apache/commons/collections4/bloomfilter/CountingLongPredicate.java, src/main/java/org/apache/commons/collections4/bloomfilter/Shape.java
This pull updates typos found in bloomfilter code by @marcwrobel  in his original work for #323.
The changes were removed from #323 because #335 already in flight and nearing merge action.
=> Collections 384 [bloomfilter] fix typos

src/main/java/org/apache/commons/collections4/iterators/ExtendedIterator.java, src/test/java/org/apache/commons/collections4/iterators/ExtendedIteratorTest.java
Implement COLLECTIONS-870
Adds an ExtendedIterator as defined in COLLECTIONS-870 as well as in the discussion on the mailing list.
mailing list discussion: https://lists.apache.org/thread/rpcsoz3jwz7x9sp3cgzf315ls7pcd90w
=> COLLECTIONS-870: Added ExtendedIterator and tests
